name: workflow-cargo-tarpaulin
run-name: cargo tarpaulin run by ${{ github.actor }}
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  cargo-tarpaulin:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:latest
      options: --security-opt seccomp=unconfined
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: check-coverage
        run: |
          cargo tarpaulin --verbose --all-features --ignore-tests --workspace --timeout 120 --fail-under 100 --out Xml

      - name: report-coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
